controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: True

joint_state_broadcaster:
  ros__parameters:
    type: "joint_state_broadcaster/JointStateBroadcaster"

diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["base_left_wheel_joint"]
    right_wheel_names: ["base_right_wheel_joint"]
    wheel_separation: 0.45
    wheel_radius: 0.1
    cmd_vel_timeout: 0.5
    publish_rate: 50
    use_stamped_vel: false
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    cmd_vel_topic: "/cmd_vel"
